#!/bin/bash

max_voltage=${1:-3800}

while true
do
    voltage=`cat /sys/class/power_supply/battery/voltage_max`
    # echo $voltage

    if [[ $voltage != $max_voltage ]]; then
        echo $max_voltage > /sys/class/power_supply/battery/voltage_max
        date=`date +[%Y.%m.%d\ %H:%M:%S]`
        echo "$date Updated voltage_max to $max_voltage"
    fi
    sleep 30
done
