#!/bin/bash

ip=192.168.0.1
gateway_interface=rmnet_data0

interface_address=`ip address | sed -n "s/.*inet \([0-9\.]*\).*$gateway_interface$/\1/p"`
if [[ -z $interface_address ]]; then
   echo "No interface address found for $gateway_interface"
   exit
fi

current_gateway=`ip route show table main | sed -n 's/default via \([0-9\.]*\).*/\1/p'`

status () {
   echo Interface address: $interface_address
   echo Default gateway: $current_gateway
}

update () {
   if [[ "$interface_address" == "$current_gateway" ]]; then
      return
   fi
   if [[ -n $current_gateway ]]; then
      echo "Removing current gateway..."
      ip route del default table main
   fi
   echo "Adding gateway..."
   ip route add default via $interface_address table main
   echo "Done."
}

case $1 in
   status)
      status
      ;;
   *)
      update
      ;;
esac
